version: '3.8'

services:
  tom_cruise_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tom_cruise_app_container
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./tom_cruise:/var/www/html
    networks:
      - tom_cruise_network
    expose:
      - "9000"  # Expose port 9000 for PHP-FPM

  tom_cruise_webserver:
    image: nginx:alpine
    container_name: tom_cruise_webserver_container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker-compose/nginx/:/etc/nginx/conf.d
    networks:
      - tom_cruise_network
    depends_on:
      - tom_cruise_app

networks:
  tom_cruise_network:
    driver: bridge
